package com.project.model;
// Generated Apr 15, 2017 8:18:30 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private BigDecimal eventid;
	private String eventtype;
	private String eventtitle;
	private String eventidentifier;
	private Date startdate;
	private Date enddate;
	private String eventdescription;
	private String custommessage;
	private String instructions;
	private String cfpProcess;
	private String eventtracks;
	private String venue;
	private Set vendors = new HashSet(0);
	private Set clients = new HashSet(0);

	public Event() {
	}

	public Event(BigDecimal eventid) {
		this.eventid = eventid;
	}

	public Event(BigDecimal eventid, String eventtype, String eventtitle, String eventidentifier, Date startdate,
			Date enddate, String eventdescription, String custommessage, String instructions, String cfpProcess,
			String eventtracks, String venue, Set vendors, Set clients) {
		this.eventid = eventid;
		this.eventtype = eventtype;
		this.eventtitle = eventtitle;
		this.eventidentifier = eventidentifier;
		this.startdate = startdate;
		this.enddate = enddate;
		this.eventdescription = eventdescription;
		this.custommessage = custommessage;
		this.instructions = instructions;
		this.cfpProcess = cfpProcess;
		this.eventtracks = eventtracks;
		this.venue = venue;
		this.vendors = vendors;
		this.clients = clients;
	}

	public BigDecimal getEventid() {
		return this.eventid;
	}

	public void setEventid(BigDecimal eventid) {
		this.eventid = eventid;
	}

	public String getEventtype() {
		return this.eventtype;
	}

	public void setEventtype(String eventtype) {
		this.eventtype = eventtype;
	}

	public String getEventtitle() {
		return this.eventtitle;
	}

	public void setEventtitle(String eventtitle) {
		this.eventtitle = eventtitle;
	}

	public String getEventidentifier() {
		return this.eventidentifier;
	}

	public void setEventidentifier(String eventidentifier) {
		this.eventidentifier = eventidentifier;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getEventdescription() {
		return this.eventdescription;
	}

	public void setEventdescription(String eventdescription) {
		this.eventdescription = eventdescription;
	}

	public String getCustommessage() {
		return this.custommessage;
	}

	public void setCustommessage(String custommessage) {
		this.custommessage = custommessage;
	}

	public String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(String instructions) {
		this.instructions = instructions;
	}

	public String getCfpProcess() {
		return this.cfpProcess;
	}

	public void setCfpProcess(String cfpProcess) {
		this.cfpProcess = cfpProcess;
	}

	public String getEventtracks() {
		return this.eventtracks;
	}

	public void setEventtracks(String eventtracks) {
		this.eventtracks = eventtracks;
	}

	public String getVenue() {
		return this.venue;
	}

	public void setVenue(String venue) {
		this.venue = venue;
	}

	public Set getVendors() {
		return this.vendors;
	}

	public void setVendors(Set vendors) {
		this.vendors = vendors;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
