/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2017-04-12 19:12:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eventmetadata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Remember Login With JSP-Servlet</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/styles1.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write(" <body>\r\n");
      out.write(" <div id=\"container\">\r\n");
      out.write("<div id=\"a\"><a href=\"AccountController?action=Logout\" >Logout</a></div>\r\n");
      out.write(" <table id=\"table\" class=\"tbl\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        \r\n");
      out.write("     \r\n");
      out.write("          <th><input align=\"right\" type=\"submit\" name=\"events\" onclick='window.location.assign(\"welcome.jsp\")' value=\"events\" id=\"events\"></th>\r\n");
      out.write("       \r\n");
      out.write("        <th><input align=\"right\" type=\"submit\" name=\"setupevent\" onclick='window.location.assign(\"eventmetadata.jsp\")' value=\"setupevent\" id=\"setupevent\"></th>\r\n");
      out.write("       </tr> \r\n");
      out.write("      </table>\r\n");
      out.write("<center><table id=\"table\" class=\"tb2\">\r\n");
      out.write("    <tr>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"100%\" height=\"100%\">\r\n");
      out.write("<center><table id=\"table1\" class=\"tb2\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>Event Details</th>\r\n");
      out.write("        <th>cpf Setup</th>\r\n");
      out.write("        <th>Review Setup</th>\r\n");
      out.write("        <th>Session Setup</th>\r\n");
      out.write("        <th>new Event</th>\r\n");
      out.write("        <th>abstract list</th>\r\n");
      out.write("       </tr> \r\n");
      out.write("      </table>\r\n");
      out.write("      <p>..............@..............................................................................................................................</p>\r\n");
      out.write("<h2>Event Metadata &nbsp client/vendor &nbsp sponsored participants </h2></center>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<!--<td width=\"15%\" valign=\"top\" align=\"center\">\r\n");
      out.write("\t\t<br/><a href=\"Login.html\">Login</a><br/>\r\n");
      out.write("\t\t<br/><a href=\"registration.html\">Register</a><br/>\r\n");
      out.write("\t</td> -->\r\n");
      out.write("\t<td valign=\"top\" align=\"center\"><br/>\r\n");
      out.write("\t\t<form action=\"eventtype.jsp\"><table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\"><b>Event Metadata</b></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\"><b>&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\tEventType:&nbsp;&nbsp;&nbsp;&nbsp;<select>\r\n");
      out.write("  \t\t\t<option value=\"meeting\">meeting</option>\r\n");
      out.write(" \t\t \t<option value=\"conference\">conference</option>\r\n");
      out.write("  \t\t\t<option value=\"discussion\">discussion</option>\r\n");
      out.write("  \t\t\t<option value=\"launch\">launch</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>eventID</td>\r\n");
      out.write("\t\t\t<td><input id=\"eventID\" type=\"text\" name=\"eventID\" required autofocus/></td>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>venueID</td>\r\n");
      out.write("\t\t\t<td><input id=\"venue\" type=\"text\" name=\"venueID\"/></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>eventTitle</td>\r\n");
      out.write("\t\t\t<td><input id=\"eventTitle\" type=\"text\" name=\"eventTitle\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>event Identifier</td>\r\n");
      out.write("\t\t\t<td><input id=\"eventidentifier\" type=\"text\" name=\"eventIdentifier\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>start date</td>\r\n");
      out.write("\t\t\t<td><input id=\"eventdate\" type=\"text\" name=\"startDate\"/></td>\r\n");
      out.write("\t\t\t<td>end date</td>\r\n");
      out.write("\t\t\t<td><input id=\"eventdate\" type=\"text\" name=\"endDate\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>Event Description</td>\r\n");
      out.write("\t\t\t<td><input id=\"description\" type=\"text\" name=\"eventDescription\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>custom message</td>\r\n");
      out.write("\t\t\t<td><input id=\"custommessage\" type=\"text\" name=\"customMessage\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>instructions</td>\r\n");
      out.write("\t\t\t<td><input id=\"instructions\" type=\"text\" name=\"instructions\"/></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>CPF_Process</td>\r\n");
      out.write("\t\t\t<td><input id=\"CPF_Process\" type=\"text\" name=\"CPF_Process\"/></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\r\n");
      out.write("             <td>Event logo:</td> <td><input type=\"file\" name=\"img\"></td>\r\n");
      out.write("             \r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>eventtrack</td>\r\n");
      out.write("\t\t\t<td><input id=\"eventtrack\" type=\"text\" name=\"eventtrack\"/></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t<input type=\"submit\" formaction=\"save\" formmethod=\"post\" value=\"save\" />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table></form>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<td><input align=\"right\" type=\"submit\" name=\"user\" onclick='window.location.assign(\"client.jsp\")' value=\"next\" id=\"next\"></td>\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
